INFO: Starting training:
        Epochs:          5
        Batch size:      1
        Learning rate:   1e-05
        Training size:   4590
        Validation size: 509
        Checkpoints:     True
        Device:          cuda
        Images scaling:  0.5
        Mixed Precision: True

Epoch 1/5:   0%|                                                                                                                                             | 0/4590 [00:27<?, ?img/s]
Traceback (most recent call last):
  File "train_pan.py", line 197, in <module>
    amp=args.amp)
  File "train_pan.py", line 92, in train_net
    masks_pred = net(images)
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "G:\내 드라이브\인턴\도로 크랙 탐지\Pytorch-UNet\pan\networks.py", line 223, in forward
    fm_high = self.fpa(fm_low)
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "G:\내 드라이브\인턴\도로 크랙 탐지\Pytorch-UNet\pan\networks.py", line 97, in forward
    x_master = self.conv_master(x)
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\site-packages\torch\nn\modules\conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\site-packages\torch\nn\modules\conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [2048, 2048, 1, 1], but got 3-dimensional input of size [3, 640, 959] instead